"""
Plain-language knowledge base for every metric and every insight widget.

METRIC_GLOSSARY[key] = {label, meaning, good, target, alpha}
  meaning : what the number is, in one sentence
  good    : what "good" looks like
  target  : what an analyst is trying to establish / the question it answers
  alpha   : how it can earn alpha or what it helps you trade

INSIGHT_EXPLAINERS[insight_id] = {intent, good, target, alpha}
  the same lens, applied to a whole widget.

Both are embedded into the report (hover tooltips + expandable "What this means &
how it earns alpha" panels) and are the source for docs/GLOSSARY.md.
"""

from __future__ import annotations

METRIC_GLOSSARY = {
    # ---- Profitability ----
    "gross_margin": dict(label="Gross margin", meaning="Share of revenue left after the direct cost of goods/services.",
        good="Higher and stable; wide gross margin signals pricing power or a cost moat.",
        target="Establish structural profitability and how much room exists to absorb cost shocks.",
        alpha="Rising gross margin ahead of consensus often precedes earnings upgrades — a long signal."),
    "ebitda_margin": dict(label="EBITDA margin", meaning="Operating cash profitability before D&A, interest and tax, as a % of sales.",
        good="Higher; consistent with peers or expanding.",
        target="Compare operating profitability across capital structures and tax regimes.",
        alpha="Margin inflection is a cleaner cross-border signal than net income, which FX and tax distort."),
    "operating_margin": dict(label="Operating margin", meaning="EBIT as a % of revenue — profit after all operating costs.",
        good="Higher and trending up; beating the peer median.",
        target="Judge core operating efficiency independent of financing.",
        alpha="Operating leverage (margin rising faster than sales) compounds EPS — buy ahead of it."),
    "net_margin": dict(label="Net margin", meaning="Bottom-line profit as a % of revenue.",
        good="Higher; positive and stable. Negative = loss-making.",
        target="Final profitability after everything, incl. tax and interest.",
        alpha="Best read relative to sector; a low-margin name that is structurally improving can re-rate hard."),
    "roe": dict(label="Return on equity", meaning="Net income divided by shareholders' equity.",
        good=">15% is strong, but check it isn't just leverage (see DuPont).",
        target="How much profit management generates on owners' capital.",
        alpha="High, non-leverage-driven ROE that the market underpays for is the classic quality-value trade."),
    "roa": dict(label="Return on assets", meaning="Net income divided by total assets.",
        good="Higher; asset-light models score well.",
        target="Profit generated per dollar of assets, ignoring how they're financed.",
        alpha="ROA gap vs peers flags who actually earns their asset base — short the laggards, own the leaders."),
    "roic": dict(label="Return on invested capital", meaning="After-tax operating profit (NOPAT) over debt+equity−cash.",
        good=">WACC (roughly >8-10%) means the company creates value; below, it destroys it.",
        target="The single best test of whether a business is worth owning.",
        alpha="ROIC > WACC and rising, bought below intrinsic value, is the core compounder trade."),
    "roce": dict(label="Return on capital employed", meaning="EBIT over capital employed (assets − current liabilities).",
        good="Higher and above cost of capital; stable through the cycle.",
        target="Pre-tax capital efficiency, useful for cross-tax-regime comparison.",
        alpha="ROCE trend separates genuine improvers from cyclical flatterers."),
    # ---- Growth ----
    "revenue_cagr": dict(label="Revenue CAGR", meaning="Compound annual revenue growth over the history window.",
        good="Higher, but durable growth beats a spiky number.",
        target="Establish the top-line trajectory and TAM capture.",
        alpha="Durable growth the market prices as temporary is where growth alpha lives."),
    "eps_cagr": dict(label="EPS CAGR", meaning="Compound annual growth in earnings per share.",
        good="Higher than revenue growth = operating leverage + disciplined share count.",
        target="Per-share value creation, the thing shareholders actually own.",
        alpha="EPS growth outrunning revenue signals leverage/buybacks — quality of the growth matters."),
    "fcf_cagr": dict(label="Free-cash-flow CAGR", meaning="Compound annual growth in free cash flow.",
        good="Positive and tracking earnings growth.",
        target="Whether growth is turning into real, distributable cash.",
        alpha="FCF growth that lags EPS growth is a red flag; the reverse is a hidden-quality long."),
    # ---- Liquidity ----
    "current_ratio": dict(label="Current ratio", meaning="Current assets over current liabilities.",
        good="~1.5-3x; comfortably above 1.",
        target="Short-term solvency — can it pay the next 12 months' bills.",
        alpha="Mainly a risk filter; deteriorating liquidity precedes distress re-ratings."),
    "quick_ratio": dict(label="Quick ratio", meaning="Liquid current assets (ex-inventory) over current liabilities.",
        good=">1 means it can cover short-term liabilities without selling inventory.",
        target="Stricter liquidity test for inventory-heavy names.",
        alpha="Risk screen for cyclicals/retail where inventory can be stranded."),
    "interest_coverage": dict(label="Interest coverage", meaning="EBIT divided by interest expense.",
        good=">4x comfortable; <2x fragile.",
        target="Can operating profit service the debt.",
        alpha="Thin coverage into a rising-rate backdrop is a short/avoid; improving coverage de-risks a re-rating."),
    # ---- Leverage ----
    "net_debt_ebitda": dict(label="Net debt / EBITDA", meaning="Net borrowings relative to operating cash profit.",
        good="<2x conservative; >4x stretched (sector-dependent — utilities carry more).",
        target="Balance-sheet risk and refinancing headroom.",
        alpha="De-leveraging stories re-rate as risk falls; over-levered names de-rate fast when growth stalls."),
    "debt_to_equity": dict(label="Debt / equity", meaning="Total debt relative to equity.",
        good="Lower; context by sector.",
        target="Capital-structure risk.",
        alpha="Leverage amplifies both ROE and downside — pair with ROIC to judge quality of returns."),
    "gearing": dict(label="Gearing", meaning="Debt as a share of total capital (debt+equity).",
        good="Lower and stable.",
        target="Overall reliance on debt funding.",
        alpha="Gearing trend flags capital-allocation discipline."),
    # ---- Efficiency / cash ----
    "asset_turnover": dict(label="Asset turnover", meaning="Revenue generated per dollar of assets.",
        good="Higher; asset-light beats asset-heavy for a given margin.",
        target="How hard the asset base works (a DuPont driver of ROE).",
        alpha="Improving turnover with steady margin lifts ROE — a quality signal the market lags."),
    "cash_conversion_cycle": dict(label="Cash conversion cycle", meaning="Days to turn working-capital investment into cash (DSO+DIO−DPO).",
        good="Lower/negative; a negative CCC funds growth with suppliers' money.",
        target="Working-capital efficiency and self-funding capacity.",
        alpha="Structural CCC improvement frees cash and lifts FCF — under-appreciated quality."),
    "fcf_conversion": dict(label="FCF conversion", meaning="Free cash flow as a % of net income — the single best earnings-quality tell.",
        good=">80-100% consistently. Persistently low = earnings not backed by cash.",
        target="Whether reported profit is real, distributable cash.",
        alpha="High, stable conversion the market ignores is prime quality-compounder alpha; falling conversion is an early short."),
    "ocf_ebitda": dict(label="OCF / EBITDA", meaning="Operating cash flow as a % of EBITDA.",
        good="Higher (>70%); low means working capital or accruals are leaking cash.",
        target="Cash backing of headline operating profit.",
        alpha="Divergence between OCF and EBITDA flags aggressive accounting — a forensic short input."),
    "capex_sales": dict(label="Capex / sales", meaning="Capital intensity — capex as a % of revenue.",
        good="Lower for a given growth rate; but under-investment can mortgage the future.",
        target="How much reinvestment the model needs to grow.",
        alpha="Capex cycles turn: peak-capex names can inflect to FCF harvest — a timing trade."),
    # ---- Valuation ----
    "pe": dict(label="Price / earnings", meaning="Market cap over net income.",
        good="Lower is cheaper, but only vs growth+quality; low P/E + low ROIC is a trap.",
        target="Headline valuation vs earnings.",
        alpha="Cheap P/E with improving quality and estimate upgrades is the value re-rating trade."),
    "ev_ebitda": dict(label="EV / EBITDA", meaning="Enterprise value over EBITDA — capital-structure-neutral valuation.",
        good="Lower vs peers, adjusted for growth/margin.",
        target="Compare valuation across different leverage and tax regimes.",
        alpha="The workhorse comp multiple; a name cheap on EV/EBITDA with high ROIC is a genuine opportunity, not a trap."),
    "ev_sales": dict(label="EV / sales", meaning="Enterprise value over revenue.",
        good="Lower for a given margin; the go-to when earnings are negative.",
        target="Value loss-making or early-stage names on revenue.",
        alpha="Re-rating happens as margins arrive — EV/sales vs margin trajectory is the growth-value cross."),
    "pb": dict(label="Price / book", meaning="Market cap over equity (book value).",
        good="Lower, but only meaningful vs ROE.",
        target="Valuation vs accounting net worth (esp. financials/utilities).",
        alpha="Low P/B + high ROE is the classic value screen; P/B alone misleads for asset-light models."),
    "p_fcf": dict(label="Price / FCF", meaning="Market cap over free cash flow.",
        good="Lower; a cash-based cheapness check.",
        target="Valuation against the cash owners can actually receive.",
        alpha="Cheaper on P/FCF than P/E means high cash conversion the market underpays — a quality-value long."),
    "fcf_yield": dict(label="FCF yield", meaning="Free cash flow divided by market cap — the cash return you buy.",
        good=">5-6% attractive; the inverse of P/FCF.",
        target="Cash return on the equity you pay for.",
        alpha="High FCF yield + growing FCF is the core cash-compounder buy signal."),
    "dividend_yield": dict(label="Dividend yield", meaning="Dividend per share over price.",
        good="Sustainable and covered by FCF; very high yields can signal risk.",
        target="Income contribution and capital-return discipline.",
        alpha="Covered, growing yield supports total return; an unsustainable yield is a value trap / dividend-cut short."),
    "peg": dict(label="PEG ratio", meaning="P/E divided by EPS growth rate.",
        good="<1 suggests growth is cheap relative to the multiple.",
        target="Reconcile valuation with growth in one number.",
        alpha="Low PEG with durable growth is the growth-at-a-reasonable-price (GARP) trade."),
    # ---- Per share ----
    "eps": dict(label="EPS", meaning="Net income per share.", good="Higher and growing.",
        target="Per-share earning power.", alpha="EPS surprise + revision trend drives short-term price."),
    "bvps": dict(label="Book value / share", meaning="Equity per share.", good="Growing over time.",
        target="Accounting net worth per share.", alpha="BVPS growth + high ROE compounds intrinsic value."),
    "dps": dict(label="Dividend / share", meaning="Declared dividend per share.", good="Growing and covered.",
        target="Income per share.", alpha="Dividend-growth streaks attract re-rating from income buyers."),
    "cfps": dict(label="Cash flow / share", meaning="Operating cash flow per share.", good="Higher than EPS = clean earnings.",
        target="Cash earning power per share.", alpha="CFPS > EPS confirms earnings quality."),
    # ---- Quality scores ----
    "altman_z": dict(label="Altman Z-score", meaning="Bankruptcy-risk composite from five ratios.",
        good=">2.99 safe · 1.81-2.99 grey · <1.81 distress.",
        target="Screen for financial-distress risk.",
        alpha="Rising Z out of the distress zone is a turnaround long; falling into it is an early short."),
    "piotroski_f": dict(label="Piotroski F-score", meaning="0-9 count of improving fundamental signals.",
        good="8-9 strong · 0-2 weak.",
        target="Is the business fundamentally getting better year on year.",
        alpha="High F-score among cheap stocks historically outperforms — a value+quality overlay."),
    "dupont_roe": dict(label="DuPont ROE", meaning="ROE decomposed into margin x asset turnover x leverage.",
        good="ROE driven by margin/turnover (quality) rather than leverage (fragile).",
        target="Understand WHY a company earns its ROE.",
        alpha="Own high-quality-driven ROE; fade leverage-driven ROE that looks superficially similar."),
    # ---- Risk ----
    "total_return": dict(label="Total return (5y)", meaning="Price return over the window.",
        good="Higher, but judge vs risk taken.", target="Realised performance.",
        alpha="Context for mean-reversion vs momentum positioning."),
    "ann_return": dict(label="Annualised return", meaning="Compounded yearly return.",
        good="Higher relative to volatility.", target="Return per year.",
        alpha="Numerator of risk-adjusted return; pair with vol."),
    "ann_vol": dict(label="Annualised volatility", meaning="Standard deviation of returns, annualised.",
        good="Lower for the same return.", target="How bumpy the ride is.",
        alpha="Position-sizing input; low-vol anomaly favours owning lower-vol names."),
    "downside_vol": dict(label="Downside volatility", meaning="Volatility of negative returns only.",
        good="Lower.", target="Bad-side risk that investors actually care about.",
        alpha="Sortino/downside focus separates genuinely defensive names from merely low-return ones."),
    "beta": dict(label="Beta", meaning="Sensitivity to the benchmark (SPY).",
        good="Context-dependent: <1 defensive, >1 aggressive.",
        target="Market-risk exposure and hedge sizing.",
        alpha="Beta-timing (add high-beta into rallies, rotate to low-beta into stress) and portfolio hedging."),
    "max_drawdown": dict(label="Max drawdown", meaning="Largest peak-to-trough decline.",
        good="Shallower (closer to zero).", target="Worst-case pain the position inflicted.",
        alpha="Drawdown depth/duration sets how large a position the book can stomach — sizing discipline."),
    "momentum_12m": dict(label="12-month momentum", meaning="Price return over ~12 months (skipping the last month).",
        good="Positive and persistent.", target="Trend strength.",
        alpha="Cross-sectional momentum is a durable factor — long winners, short losers."),
    "sharpe": dict(label="Sharpe ratio", meaning="Excess return per unit of volatility.",
        good=">1 good; higher is better.", target="Risk-adjusted return quality.",
        alpha="Rank names on risk-adjusted return, not raw return, to build a more efficient book."),
    # ---- Factors ----
    "value": dict(label="Value factor (z)", meaning="Cross-sectional cheapness score (cheap = high).",
        good="Positive = cheaper than the universe.", target="Systematic cheapness rank.",
        alpha="Value premium: tilt toward high-value-z, avoid crowded expensive names."),
    "quality": dict(label="Quality factor (z)", meaning="Composite of ROIC, FCF conversion, margin, low leverage.",
        good="Positive = higher quality.", target="Systematic quality rank.",
        alpha="Quality premium: durable compounders outperform on a risk-adjusted basis."),
    "growth": dict(label="Growth factor (z)", meaning="Composite of revenue and EPS growth.",
        good="Positive = faster-growing.", target="Systematic growth rank.",
        alpha="Growth tilt works when durable and not over-paid (combine with value)."),
    "momentum": dict(label="Momentum factor (z)", meaning="Standardised 12-month price momentum.",
        good="Positive = trending up.", target="Systematic trend rank.",
        alpha="Momentum factor: long the top, manage the reversal risk at extremes."),
    "composite": dict(label="Composite score", meaning="Equal-weight average of value+quality+growth+momentum z-scores.",
        good="Higher = better all-round on the four factors.", target="One-number multi-factor rank.",
        alpha="A prototype systematic screen: the top decile is the deep-dive shortlist."),
}

INSIGHT_EXPLAINERS = {
    "pm_valuation": dict(
        intent="Give the PM a one-glance read of where every name trades vs its sector on the four multiples that matter.",
        good="Names sitting below the universe median on EV/EBITDA while scoring high on ROIC.",
        target="Separate genuine cheapness from value traps before allocating capital.",
        alpha="Buy cheap-and-high-return, avoid cheap-and-low-return — the core valuation-discipline trade."),
    "pm_quality_val": dict(
        intent="Plot cheapness (EV/EBITDA) against quality (ROIC) so the trade-off is visual.",
        good="Companies in the top-left: cheap and high-return.",
        target="Find where the market is mispricing quality.",
        alpha="Top-left names are the highest-conviction longs; bottom-right are funding shorts/avoids."),
    "pm_commentary": dict(
        intent="Turn the numbers into a written brief a PM can read in 30 seconds, every claim traceable.",
        good="A short list of cheap-quality longs and a clean watch-list of red flags.",
        target="Collapse 32x40 data points into an actionable narrative.",
        alpha="Speeds conviction and surfaces the shortlist worth deep due-diligence first."),
    "pm_capital_return": dict(
        intent="Show income contribution across the book at a glance.",
        good="Covered, growing yields — not the highest yield, the most sustainable.",
        target="Balance income vs growth in the blend.",
        alpha="Covered-yield compounders anchor total return; unsustainable yields are dividend-cut shorts."),
    "hoi_sector_heat": dict(
        intent="A capital-allocation heatmap: which theme is cheap, high-quality, growing, and clean on leverage.",
        good="Themes combining reasonable multiples with high ROIC and strong FCF conversion.",
        target="Decide where to lean the book at the theme level.",
        alpha="Top-down tilt toward the best risk-adjusted theme is a repeatable source of allocation alpha."),
    "hoi_cheap_quality": dict(
        intent="The intersection of the value and quality factors — the shortlist that is both cheap and good.",
        good="Names positive on BOTH value-z and quality-z.",
        target="Prioritise scarce research time on the best-odds ideas.",
        alpha="Cheap+quality is the most reliable factor combination for forward excess return."),
    "hoi_risk_register": dict(
        intent="A governance view of everything tripping a distress, cash-quality, leverage or profitability flag.",
        good="An empty or shrinking register.",
        target="Ensure no position carries an unexamined red flag.",
        alpha="Avoiding blow-ups is negative-alpha-avoidance — often worth more than the next winner."),
    "pa_comps": dict(
        intent="The analyst workhorse: the full ratio set for all 32 names, percentile-shaded so best-in-class is obvious.",
        good="Dark-green cells clustering on one name = a broad-based quality leader.",
        target="Rank a peer set across profitability, growth, cash, leverage and valuation at once.",
        alpha="Fast, consistent comps replace hours of spreadsheet work and surface mispriced quality."),
    "pa_dupont": dict(
        intent="Break ROE into margin x asset turnover x leverage to see HOW the return is earned.",
        good="ROE driven by margin and turnover, not leverage.",
        target="Judge the quality and durability of returns.",
        alpha="Own high-quality-driven ROE; short/avoid names whose ROE is just balance-sheet gearing."),
    "pa_fcf_trend": dict(
        intent="Track FCF-to-net-income over five years — the clearest earnings-quality signal.",
        good="Persistently above ~80%; stable or rising.",
        target="Confirm reported profit is backed by cash.",
        alpha="Deteriorating conversion is an early short; hidden high conversion is a quality-compounder long."),
    "qa_factors": dict(
        intent="A systematic value/quality/growth/momentum scorecard and composite rank.",
        good="High composite with balanced positive factor exposures.",
        target="Prototype a repeatable, rules-based screen.",
        alpha="The top of the composite rank is a factor-tilted long book; the bottom funds it."),
    "qa_corr": dict(
        intent="Pairwise return correlations for signal and structure detection.",
        good="Tight clusters (pairs) and low cross-cluster correlation (diversifiers).",
        target="Find pair-trade candidates and understand co-movement.",
        alpha="High-correlation pairs enable relative-value/pairs trades; low correlation improves the book's efficiency."),
    "qa_perf": dict(
        intent="Measure how fast the free-tier API returns each dataset and how many names fit the daily cap.",
        good="Low latency, all endpoints 200-OK, ample companies-per-budget.",
        target="Size what is operationally feasible on the free tier.",
        alpha="Data-ops reality check — governs refresh cadence and universe size for any live signal."),
    "pr_riskstats": dict(
        intent="Return, volatility, beta, drawdown and Sharpe for every name vs the benchmark.",
        good="High Sharpe, contained drawdown, beta appropriate to the mandate.",
        target="Judge names on risk-adjusted, not raw, return.",
        alpha="Building the book on Sharpe and drawdown, not headline return, raises realised risk-adjusted alpha."),
    "pr_drawdown": dict(
        intent="Show the growth-of-$100 path and the drawdown it took to get there.",
        good="Steady compounding with shallow, short drawdowns.",
        target="Understand the pain a position inflicts before sizing it.",
        alpha="Drawdown-aware sizing keeps positions survivable through stress — the discipline that preserves alpha."),
    "pr_corr": dict(
        intent="The correlation matrix read for portfolio construction rather than signals.",
        good="A spread of low/negative correlations across the book.",
        target="Assemble genuinely diversifying exposures.",
        alpha="Combining uncorrelated return streams raises the book's Sharpe — diversification is the only free lunch."),
}


def enrich_calc(metric_key: str, calc: dict) -> dict:
    g = METRIC_GLOSSARY.get(metric_key)
    if g:
        calc = dict(calc)
        calc["glossary"] = g
    return calc
